name: Build Integration

on:
  push:
    branches:
      - '!master'
      - '!develop'
      - '*'

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: KtLint
        run: bash ./gradlew ktlintCheck
  sdk:
    name: Generate SDK
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build SDK
        run: bash ./gradlew :sdk:assemble --stacktrace
  apk:
    name: Generate APK
    needs: sdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew :app:assemble --stacktrace