name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: KtLint
        run: bash ./gradlew ktlintCheck
  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Sdk Unit Tests
        run: bash ./gradlew :sdk:testDebugUnitTest --stacktrace 
      - name: App Unit Tests
        run: bash ./gradlew :app:testDebugUnitTest --stacktrace 
      - name: App Instrumented Test
        run: bash ./gradlew :app:assembleDebugAndroidTest --stacktrace
  sdk:
    name: Generate SDK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build SDK
        run: bash ./gradlew :sdk:assembleRelease --stacktrace
  apk:
    name: Generate APK
    needs: sdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew :app:assembleRelease --stacktrace